
* Config :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval yes
  (setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
  (add-to-list 'org-latex-classes
	       '("altacv_jj1" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

  % Change the page layout if you need to
  \\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

  % Use roboto and lato for fonts
  \\renewcommand{\\familydefault}{\\sfdefault}

  % Change the colours if you want to
  \\definecolor{SlateGrey}{HTML}{2E2E2E}
  \\definecolor{LightGrey}{HTML}{666666}
  \\definecolor{DarkPastelRed}{HTML}{450808}
  \\definecolor{PastelRed}{HTML}{8F0D0D}
    \\definecolor{midnightblue}{HTML}{191970}
  \\definecolor{GoldenEarth}{HTML}{E7D192}
  \\colorlet{name}{black}
  \\colorlet{tagline}{PastelRed}
  \\colorlet{heading}{PastelRed}
  \\colorlet{headingrule}{GoldenEarth}
  \\colorlet{subheading}{PastelRed}
  \\colorlet{accent}{PastelRed}
  \\colorlet{emphasis}{SlateGrey}
  \\colorlet{body}{LightGrey}

  % Change some fonts, if necessary
  \\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
  \\renewcommand{\\personalinfofont}{\\footnotesize}
  \\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
  \\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

  % Change the bullets for itemize and rating marker
  % for \cvskill if you want to
  \\renewcommand{\\itemmarker}{{\\small\\textbullet}}
  \\renewcommand{\\ratingmarker}{\\faCircle}
  "

		 ("\\cvsection{%s}" . "\\cvsection*{%s}")
		 ("\\cvevent{%s}" . "\\cvevent*{%s}")))
  (setq org-latex-packages-alist 'nil)
  ;; (setq org-latex-default-packages-alist
  ;;       '(("rm" "roboto"  t)
  ;;         ("defaultsans" "lato" t)
  ;;         ("" "paracol" t)
  ;;         ))
#+END_SRC

* Latex Preamble                                                   :noexport:
#+LATEX_CLASS: altacv_jj1
#+LATEX_HEADER: \usepackage{paracol}
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
** org preamble
#+AUTHOR: Didier Jérémie Juste
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1 tag:nil
** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* CV Header                                                          :ignore:
** Photo & Tagline                                                   :ignore:
#+begin_export latex
\name{Didier Jérémie Juste}
%\photoR{0.5cm}{~/Pictures/profile/didier-jeremie-juste-cropped.jpg}
\tagline{PhD in Economics / Data Scientist}
#+end_export

#+begin_src emacs-lisp :exports none
(setq org-latex-with-hyperref nil)
#+end_src

#+RESULTS:

** Personal Info                                                     :ignore:
#+begin_export latex
\personalinfo{
  \homepage{https://jeremiejuste.gitlab.io/}
  \email{jeremiejuste@gmail.com}
  \phone{+33 6 18 82 77 61}
  \github{djj88}
  \linkedin{djj88}
  \location{Frankfurt am Main, DE}
    \location{Open for relocation}
    \lastedited{updated on \today}
}
\makecvheader
#+end_export
* Quotes                                                             :ignore:

#+begin_export latex
 \begin{quote}
 ``I am a Data Scientist with extensive training in Economics and Econometrics. I use economic theory to get insights but when it is not possible, I like to design cheap experiments that provide valuable insights using data. Over the years I learned that Cost Benefit Analysis is a key skill as ressources are limited and have alternative uses.''
 \end{quote}
#+end_export

* CV Column 1 :ignore:
#+begin_export latex
\begin{paracol}{1}
#+end_export


** Experience
*** Data Scientist                                                   :ignore:
{{{cvevent(Data Scientist,I.D. Inspiring Development, Oct 2020 -- Apr 2024, Frankfurt\, DE)}}}

# Researching methods for probabilistic inference and control in multimodal dynamical systems. EPSRC Centre for Doctoral Training in Future Autonomous and Robotic Systems (FARSCOPE).
I was given the responsibility to improve the ETL procedure with the view of increasing the capacity of the team without substantial increase in costs. I met this target by decreasing the ETL computing time eight folds, giving the team more resources to increase the value of the service. I also train the team to efficient data maniputaion in R and to improve communication through git commits. Besides, I improved methodologies to model credit risk (PD, LGD, EAD, Backtesting) so that much more risk scenarios could be explored easily. Overall, the team successfully assessed the portfolio of more that 30 banks and microfinance institutions over three years.

{{{cvtag(Improve ETL)}}}
{{{cvtag(Backend Development)}}}
{{{cvtag(IFRS9)}}}

*** CNRS Postdoctoral Researcher                                     :ignore:
{{{par-div}}}
{{{cvevent(CNRS Postdoctoral Researcher, CAMS EHESS,Sept 2019 -- Aug 2022, Paris\, Fr)}}}
I built a web application to visualize the demand and supply of jobs of the job platform Qapa using Dataiku DSS and analyze the  performance of the job matching algorithm of Qapa. A topic of interest was the analysis of the bias of the algorithm.

{{{cvtag(Feature Engineering)}}}
{{{cvtag(Machine Learning)}}}
{{{cvtag(Web development)}}}


*** Teaching Assistant                                               :ignore:
{{{par-div}}}
{{{cvevent(Teaching Assistant,CY Cergy Paris University, Sept 2013 -- Aug 2019, Paris\, Fr)}}}
I taught Financial Econometrics, Time Series Econometrics at the graduate level. A particular accent was made in testing Unit root. ARMA model, Times Series Forecasting and VAR.  I also taught Microeconomics, Macroeconomics Probability and Statistics at the undergraduate level.

{{{cvtag(Encourage Autonomous Learning)}}}
{{{cvtag(Teaching to Mastery)}}}
{{{cvtag(Regular Feedback)}}}


** Publications                                                    :noexport:
#+begin_export latex
\nocite{*}
% \printbibliography[heading=pubtype,title={\printinfo{\faBook}{Books}},type=book]
% \divider
% \printbibliography[heading=pubtype,title={\printinfo{\faFile*[regular]}{Journal Articles}},type=article]
% \divider
\printbibliography[heading=pubtype,title={\printinfo{\faUsers}{Conference Proceedings}},type=inproceedings]
#+end_export

** Projects                                                        :noexport:


** Newpage                                                  :ignore:noexport:
{{{new-page}}}



** Newpage :ignore:noexport:
{{{new-page}}}




** Education
{{{cvevent(PhD\ in  Economics, CY Cergy Paris University, Sept 2012 - Dec 2018,)}}}
- \faBook [[https://theses.fr/2018CERG0982][Three Essays on Credit Risk at the Micro and Macro Level in Microfnance and on the Hedonic Price Estimation of School Quality]]
Chapters:
  - Borrower Default in Microfinance: Evidence from a Crowdfuncing Platform
  - Competition, Fast Growth and Commercialization: Systemic Credit Risk in Microcredit Markets
  - Estimating the Effect of a School Choice Program on the Price of School Quality in Seoul

{{{divider}}}

{{{cvevent(Advanced Master in Business Administration Research, ESSEC Business School, Sept 2012 -- Aug 2013)}}}

{{{cvevent(Master in Economic Analysis, CY Cergy Paris University, Sept 2011 -- Aug 2012)}}}

{{{cvevent(Master 1 in Quantitative Economics and Economic Engineering, CY Cergy Paris University, Sept 2010 -- Aug 2011 )}}}
** Skills
Data Science Stack
{{{cvtag(Python)}}}
{{{cvtag(TensorFlow)}}}
{{{cvtag(fastai)}}}
{{{cvtag(NumPy)}}}
{{{cvtag(SciPy)}}}
{{{cvtag(Matplotlib)}}}
{{{cvtag(Pandas)}}}
{{{cvtag(R)}}}
{{{cvtag(Shiny)}}}
{{{cvtag(SQL)}}}

{{{divider}}}

Computing Skills
{{{cvtag(Test Driven Development)}}}
{{{cvtag(Functional Programming)}}}
{{{cvtag(Version Control (Git))}}}
{{{cvtag(GNU/Linux)}}}

{{{divider}}}

Software
{{{cvtag(Dataiku DSS)}}}
{{{cvtag(LaTeX)}}}
{{{cvtag(Org-mode)}}}
{{{cvtag(emacs)}}}

{{{divider}}}

Fluent in the following languages
{{{cvtag(English)}}}
{{{cvtag(French)}}}

** Courses and  Certifications
- Dataiku DSS [[https://verify.skilljar.com/c/28v5h2mxkzox][Advanced Designer]]
- [[https://verify.skilljar.com/c/vr6xzgeqdov3][Dataiku DSS Developer Certificate]]  


** Participation to Conferences and Talks
- Competition, Fast Growth and Commercialization: Systemic Credit Risk in Microcredit Markets: A Copula Approach,
  - Quantitative Finance and Financial Econometrics International Conference, Marseilles,2019
  - Econometric Society China Meeting, Shanghai, China, 2019
  - Thema Lunch Seminar CY Cergy-Paris University France, 2019
  

#     \item[] \textbf{\textbf{Competition, Fast Growth and Commercialization: Systemic Credit Risk in Microcredit Markets: A Copula Approach}}\\
#       \begin{tabular}{L!{\VRule}R}
#      2019&  Quantitative Finance and Financial Econometrics International Conference (Marseille)  \\
#      2018&  UCP PhD Seminar (Université de Cergy-Pontoise)\\
#             & Présenté sous le titre de Modeling Credit Risk in Microfinance \\
#      2018&  Econometric Society China Meeting, Shanghai \\
#      2018&  Thema Lunch Seminar (Université de Cergy-Pontoise)\\ 
#   \end{tabular}
# \end{itemize}


#+begin_export latex
\end{paracol}
\end{document}
#+end_export




